#!/bin/bash
# Prompt for required variables for building
read -p "Enter the Firebase project: " FIREBASE_PROJECT
read -p "Enter android package name: " ANDROID_PACKAGE
read -p "Enter ios bundle id: " IOS_BUNDLE
read -p "Enter web app id: " WEB_APP_ID

if ! command -v firebase &> /dev/null; then
    echo -e "Firebase tools not found. Installing..."
    curl -sL https://firebase.tools | bash
else
    echo -e "Firebase tools already installed."
fi

firebase login

FLUTTER_ROOT_PACKAGE="$(./get_main_package)"
cd "$FLUTTER_ROOT_PACKAGE" || exit 1

dart pub global activate flutterfire_cli 1.1.0

flutterfire configure --project="${FIREBASE_PROJECT}" \
--android-package-name="${ANDROID_PACKAGE}" \
--ios-bundle-id="${IOS_BUNDLE}" \
--web-app-id="${WEB_APP_ID}" \
--platforms=android,ios,web \
--yes